on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Landkreise_COVID-19-Impfungen.csv
          downloaded_filename: Aktuell_Deutschland_Landkreise_COVID-19-Impfungen.csv
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate plots
        run: |
          python generate_plots.py
      - name: Commit new plots
        run: |
          git add stacked-bars.png daily-counts.png daily-numbers.png
          git commit -a --allow-empty-message -m ''
          git push origin master
